### PR TITLE
(ISSUES) Make sdio_nand_extractor OS independant

### PR DESCRIPTION
**Pull request by mariogamer2**
This would be great to use an universal GUI lib,like GTK+ or Qt.

### CODE REVIEW

**Comment by dimok789** [comment]
What is this pull request about? Wasn't FIX94 already syncing the repos? It also has conflicts.

**Comment by mariogamer2** [comment]
I mean,this is not a PR, I maked it here because fork don't have issues enabled by default.

**Comment by mariogamer2** [comment]
You should ennable issue

**Comment by mariogamer2** [comment]
Moved to https://github.com/dimok789/sdio_nand_manager/issues/1

**Pull request closed without merging**
